version: '3'

services:
  server:
    build:
      context: ../.
      dockerfile: docker/nginx/Dockerfile
    image: ngnix-server
    volumes: 
      - ./../env/wordpress:/home/wordpress/wordpress
    ports:
      - "8080:80"
    links:
      - fpm:fpm

  fpm:
    build:
      context: ../.
      dockerfile: docker/php-pfm/Dockerfile
    volumes: 
      - ./../env/wordpress:/home/wordpress/wordpress
    ports:
      - "9000:9000"

  # db:
  #   image: mysql:5.7
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: somewordpress
  #     MYSQL_DATABASE: wordpress
  #     MYSQL_USER: wordpress
  #     MYSQL_PASSWORD: wordpress

  # wordpress:
  #   depends_on:
  #     - db
  #   image: wordpress:latest
  #   ports:
  #     - "8000:80"
  #   restart: always
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: wordpress
  #   volumes:
  #     - db_data:
  #     - ./../env/wordpress:/home/wordpress/wordpress
