version: '3'

services:
  server:
    build:
      context: ../.
      dockerfile: docker/nginx/Dockerfile
    image: ngnix-server
    volumes: 
      - ./../env/wordpress:/home/wordpress/wordpress
    ports:
      - "8080:80"
    links:
      - fpm:fpm

  fpm:
    build:
      context: ../.
      dockerfile: docker/php-pfm/Dockerfile
    volumes: 
      - ./../env/wordpress:/home/wordpress/wordpress
    ports:
      - "9000:9000"
    links:
      - db:db
  db:
    image: mariadb:5.5
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
